### ISSUE TITLE
Nemo filemanager support?

### ISSUE THREAD

**Issue by sollie78** [Diaoul/nautilus-subliminal#2]
I use Linux Mint alot. Is this compatible?

**Comment by Diaoul** [comment]
Yes. Nautilus and Nemo are supported. For Nemo, check out the [nemo branch](https://github.com/Diaoul/nautilus-subliminal/tree/nemo)

**Comment by sollie78** [comment]
Cloning subliminal-nautilus (nemo branch)...Cloning into '/tmp/tmp.xgY0pVoD8s'...remote: Counting objects: 23, done.remote: Compressing objects: 100% (13/13), done.remote: Total 23 (delta 8), reused 19 (delta 8), pack-reused 0Unpacking objects: 100% (23/23), done.Checking connectivity... done.sh: 46: pusd: not foundsollie@Sollie-Laptop ~ $

**Comment by sollie78** [comment]
This is what i ment. I cant get the command working.

Op za, 2 jan 2016 om 8:16 , schreef Harm de Vries <harmdevries@live.nl>:

**Comment by Diaoul** [comment]
Fixed with 2e255a267395540d6da895af8d6c4365dcba6194

**Comment by sollie78** [comment]
Now i get this:

Checking connectivity... done.
sh: 46: pushd: not found
sollie@Sollie-Laptop ~ $

**Comment by sollie78** [comment]
I got it:
wget https://raw.githubusercontent.com/Diaoul/nautilus-subliminal/nemo/install.sh -O - | sudo bash

I changed sh to bash.

The plugin is enabled. I can see it with right click. The download works (it download default eng subtitle) But i cant choose or config. It wont open the menu.

**Comment by Diaoul** [comment]
Which version of Linux Mint are you using?

**Comment by sollie78** [comment]
sollie@Sollie-Laptop ~ $ lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 17.3 Rosa
Release:    17.3
Codename:   rosa

sollie@Sollie-Laptop ~ $ nemo --version
nemo 2.8.6
