### ISSUE TITLE
Nemo: popup menu not working  (Linux Mint Rosa)

### ISSUE THREAD

**Issue by sollie78** [Diaoul/nautilus-subliminal#3]
The plugin is enabled. I can see it with right click. The download works (downloaded default eng. subtitle). But i can not choose or config. It will not open the menu.

sollie@Sollie-Laptop ~ $ lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description: Linux Mint 17.3 Rosa
Release: 17.3
Codename: rosa

sollie@Sollie-Laptop ~ $ nemo --version
nemo 2.8.6

PS: I installed nautlis. Same problem!

**Comment by sollie78** [comment]
Is the a way i can execute the command from terminal. Maybe it gives me some information?

**Comment by sollie78** [comment]
sollie@Sollie-Laptop ~ $ nautilus
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus-subliminal.py", line 180, in choose_callback
    builder.add_from_file(os.path.join(os.path.dirname(**file**), 'subliminal', 'ui', 'choose.glade'))
gi._glib.GError: /usr/share/nautilus-python/extensions/subliminal/ui/choose.glade: required gtk+ version 3.12, current version is 3.10

**Comment by Diaoul** [comment]
OK, I suspected it was something like that. I lowered the requirements of GTK+ with 67453cf41825ff0e90dc064ff2d6765f7e8fb516. Reinstall and let me know if that works.

**Comment by sollie78** [comment]
sollie@Sollie-Laptop ~ $ nautilus
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus-subliminal.py", line 269, in config_callback
    builder.add_from_file(os.path.join(os.path.dirname(__file__), 'subliminal', 'ui', 'config.glade'))
gi._glib.GError: /usr/share/nautilus-python/extensions/subliminal/ui/config.glade: required gtk+ version 3.12, current version is 3.10

Almost :)

**Comment by sollie78** [comment]
I had to restart nautilus. Its working. Thanks.

**Comment by sollie78** [comment]
![schermafdruk van 2016-01-04 23 51 06](https://cloud.githubusercontent.com/assets/1428384/12109184/eea9db08-b37f-11e5-99d2-9eecb6d6f1fd.png)
![schermafdruk van 2016-01-04 23 50 41](https://cloud.githubusercontent.com/assets/1428384/12109185/eec0c28c-b37f-11e5-8044-f542efaa4a76.png)

The list is a little short. Cosmetic glitch.
Date: Mon, 4 Jan 2016 14:21:18 -0800

**Comment by Diaoul** [comment]
Can you join à screenshot?

**Comment by sollie78** [comment]
See priveous message.

**Comment by sollie78** [comment]
When i not set language code on. It cant dowload two items?

Plex mediaserver works with 3 letter language code. Is this possible.

Nederland, nl, dut
English, en, eng

**Comment by Diaoul** [comment]
Hold CTRL to select multiple languages.

**Comment by sollie78** [comment]
I know. I select eng and dutch. But when i use the download butten it can download only 1 when language code is off.

**Comment by Diaoul** [comment]
What did you expect? You can't put 2 subtitles in a single .srt file. It's better to keep the language code in the filename. Most media players can detect those subtitles.

**Comment by sollie78** [comment]
i also think that is the best way. You can close this one.

**Comment by Diaoul** [comment]
Margins fixed with https://github.com/Diaoul/nautilus-subliminal/pull/4
