### ISSUE TITLE
install script is not working

### ISSUE THREAD

**Issue by legz** [Diaoul/nautilus-subliminal#5]
The install script seems not working on Linux Mint 17.3 :

```
Installing necessary packages...
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
python-nemo est déjà la plus récente version disponible.
git est déjà la plus récente version disponible.
python-pip est déjà la plus récente version disponible.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 15 non mis à jour.
Cloning subliminal-nautilus (nemo branch)...
Clonage dans '/tmp/tmp.nAmUsfLu7s'...
remote: Counting objects: 23, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 23 (delta 8), reused 16 (delta 7), pack-reused 0
Unpacking objects: 100% (23/23), done.
Vérification de la connectivité... fait.
install.sh: 46: install.sh: pushd: not found
```

I think the "pushd ${TMP_DIR}" command is incorrect : pushd syntax is "pushd myDir/" and not "pushd myDir".

**Comment by Diaoul** [comment]
It seems the issue is pushd isn't found. Not a directory issue I'd say. Does your system have pushd?

**Comment by legz** [comment]
Pushd is correctly installed on my system, and : 
- when I tried "pushd myDir" in the terminal I get the same error 
- when I tried "pushd myDir/" in the terminal everything was working fine
- I "fixed" the problem hardcoding this 2 lines : 

```
TMP_DIR="tmp_dir"
[...]
pushd tmp_dir/
```

(yes it's a dirty fix but I'm not very good _and_ I wanted to watch my movie with subtitles:) )

**Comment by legz** [comment]
Update : I just tried the install.sh script again and everything was working fine.
The only things that changed is a reboot. ¯\_(ツ)_/¯

**Comment by timothymowens** [comment]
The commands you provide to install these should be changed from:
`wget https://raw.githubusercontent.com/Diaoul/nautilus-subliminal/master/install.sh -O - | sudo sh`
to:
`wget https://raw.githubusercontent.com/Diaoul/nautilus-subliminal/master/install.sh -O - | sudo bash`

**Comment by Diaoul** [comment]
Actually not everybody uses bash so I cannot make that switch. It's weird though that some sh don't come with basic pushd/popd.
