### ISSUE TITLE
Feature Request: download cover from IMDB

### ISSUE THREAD

**Issue by ComputingFroggy** [Diaoul/nautilus-subliminal#6]
Hi,

It will be nice if the script would download the cover from IMDB (in a file named cover.jpg ... or the file name could be defined in the configuration). Of course, this would be an option activated in the configuration.

opensubtitles.org displays it ! ;-)
So even with Subliminal I still go to opensubtitles.org, to get the IMDB page of the movie and display then download the cover (the one from opensubtitles.org is too small).

Thanks for a great script anyway.

BTW, the install script stopped at line 46 (pushd). I don't understand why, but I ran the rest of the script manually and it's all OK.

**Comment by Diaoul** [comment]
This is out of scope for subliminal, I think other tools can do that.
