### ISSUE TITLE
One line installation not working. install.sh not working either.

### ISSUE THREAD

**Issue by slarrain** [Diaoul/nautilus-subliminal#8]
Hi,

First, I would like to thank you for this. Looks like a great tool.

But I couldn't get it to run with neither of the one line installation methods (wget or curl):

`santiago@sle-linux-Precision-5510:~$ wget https://raw.githubusercontent.com/Diaoul/nautilus-subliminal/master/install.sh -O - | sudo sh`

`--2016-08-19 14:19:58--  https://raw.githubusercontent.com/Diaoul/nautilus-subliminal/master/install.sh`

`Resolving raw.githubusercontent.com (raw.githubusercontent.com)... [sudo] password for santiago: 151.101.56.133`

`Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.56.133|:443... connected.`

`HTTP request sent, awaiting response... 200 OK`

`Length: 2457 (2.4K) [text/plain]`

`Saving to: ‘STDOUT’'

`100%[======================================>] 2,457       --.-K/s   in 0s`

`2016-08-19 14:19:59 (51.4 MB/s) - written to stdout [2457/2457]`
and  nothing happend to I had to CTRL-C  ti stop the process.

With curl:
`santiago@sle-linux-Precision-5510:~$ curl -fsSL https://raw.githubusercontent.com/Diaoul/nautilus-subliminal/master/install.sh -O - | sudo sh`

`[sudo] password for santiago: curl: option -: is unknown`

`curl: try 'curl --help' or 'curl --manual' for more information`

I am using Ubuntu 14.04.

So I downloaded manually the install.sh file, and did:

> santiago@sle-linux-Precision-5510:~/Downloads$ sudo sh install.sh 
> [sudo] password for santiago: 
> Installing necessary packages...
> Reading package lists... Done
> Building dependency tree  
> Reading state information... Done
> python-nautilus is already the newest version.
> python-nautilus set to manually installed.
> git is already the newest version.
> python-pip is already the newest version.
> 0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
> Cloning subliminal-nautilus...
> Cloning into '/tmp/tmp.G0Lqrt6uEK'...
> remote: Counting objects: 23, done.
> remote: Compressing objects: 100% (15/15), done.
> remote: Total 23 (delta 8), reused 16 (delta 6), pack-reused 0
> Unpacking objects: 100% (23/23), done.
> Checking connectivity... done.
> install.sh: 46: install.sh: pushd: not found

So I eventually just clone the repository and then `sudo ./install.sh` and that seemed to work.

**Comment by Diaoul** [comment]
See #9
